DataSet

In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train): #@save
    """构造⼀个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)#is_train代表是否随机打乱

In [4]:
batch_size = 10
data_iter = load_array((features, labels), batch_size,True)

In [5]:
next(iter(data_iter))

[tensor([[ 0.0370,  1.0212],
         [ 0.8290, -0.4577],
         [ 1.0180, -0.5099],
         [ 0.4844,  0.6082],
         [ 2.2630,  0.4033],
         [ 0.9797, -0.0981],
         [-0.4407,  0.5091],
         [ 0.0709,  1.8904],
         [ 0.7633,  0.0347],
         [ 1.7189, -0.6085]]),
 tensor([[ 0.7959],
         [ 7.4063],
         [ 7.9732],
         [ 3.1206],
         [ 7.3306],
         [ 6.4868],
         [ 1.5990],
         [-2.0845],
         [ 5.6104],
         [ 9.6796]])]

Model

In [6]:
# nn是神经⽹络的缩写
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))#Sequential类自动将输入输出连接在一起

In [7]:
print(net)
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)


tensor([0.])

In [8]:
loss = nn.MSELoss()#损失函数

In [9]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)#优化函数

Train

In [15]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    print(net(X))
    print(netweight)
    print(net[0])
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

tensor([[ 5.2610],
        [ 6.3349],
        [13.2259],
        [ 5.2126],
        [-2.2185],
        [ 5.2103],
        [ 5.3062],
        [ 2.1411],
        [ 1.5595],
        [-3.1493]], grad_fn=<AddmmBackward0>)


NameError: name 'weight' is not defined

In [11]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([-0.0015, -0.0005])
b的估计误差： tensor([0.0007])
